steps:
  # 1. Pobierz ("Wypożycz") klucz z Secret Managera
  # To zapewnia, że klucz istnieje. Jeśli nie (błąd 404/403), build tutaj PADNIE i nie uruchomi kontenera.
  # Klucz trafia do wolumenu /workspace, który jest współdzielony i ulotny (znika po buildzie).
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'secrets'
      - 'versions'
      - 'access'
      - 'latest'
      - '--secret=avb-private-key'
      - '--out-file=cyber_rsa4096_private.pem'

      - '--out-file=cyber_rsa4096_private.pem'

  # 1b. Spróbuj pobrać poprzedni obraz (dla Cache'a)
  # "|| exit 0" zapewnia, że błąd (np. brak obrazu przy pierwszym uruchomieniu) nie przerwie builda.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/pixel-automator:latest || exit 0']

  # 2. Zbuduj obraz (Docker) z wykorzystaniem Cache'a
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/pixel-automator:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/pixel-automator:latest',
      '.'
    ]

  # 3. Uruchom Automator
  - name: 'gcr.io/$PROJECT_ID/pixel-automator:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Przenosimy klucz z workspace do miejsca, gdzie skrypt go szuka
        cp /workspace/cyber_rsa4096_private.pem /app/cyber_rsa4096_private.pem
        
        # Uruchamiamy
        cd /app && python3 pixel_automator.py
    env:
      - '_DEVICE_CODENAME=${_DEVICE_CODENAME}'
      - '_BUCKET_NAME=${_BUCKET_NAME}'
      - 'CACHE_BUCKET_NAME=${_CACHE_BUCKET_NAME}'
    volumes:
      - name: 'build_output'
        path: '/app/output'
    # ... (reszta bez zmian)

# ... (reszta pliku jest OK, tylko na końcu dodajemy images)

images:
  - 'gcr.io/$PROJECT_ID/pixel-automator:latest'
  
substitutions:
  _DEVICE_CODENAME: 'frankel'
  _BUCKET_NAME: ''      # Must be provided by the Trigger
  _CACHE_BUCKET_NAME: '' # Must be provided by the Trigger
  _WEB_BUCKET_NAME: ''   # Must be provided by the Trigger

timeout: '3600s' 
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

  # 4b. Upewnij się, że output jest dostępny (debug)
  - name: 'ubuntu'
    volumes:
      - name: 'build_output'
        path: '/workspace/output'
    args: ['ls', '-la', '/workspace/output']

    
  # 4. Wyślij wyniki
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    volumes:
      - name: 'build_output'
        path: '/workspace/output'
    args:
      - '-c'
      - |
        RESULT_FILE=$(find /workspace/output -name "ksu_patched_*.zip" | head -n 1)
        if [ ! -z "$$RESULT_FILE" ]; then
          DATE=$(date +%Y%m%d)
          FILENAME=$(basename "$$RESULT_FILE")
          # 1. Główny ZIP
          gsutil cp "$$RESULT_FILE" gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$$DATE/$$FILENAME
          
          # 2. Sygnatura Custota
          if [ -f "$$RESULT_FILE.csig" ]; then
             gsutil cp "$$RESULT_FILE.csig" gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$$DATE/$$FILENAME.csig
          fi
          
          # 3. Raport JSON
          if [ -f "/workspace/output/build_status.json" ]; then
             gsutil cp /workspace/output/build_status.json gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$$DATE/info.json
          fi
          
          # 4. Folder z obrazami (BOOT/INIT_BOOT + AVB Key)
          BASENAME="$${FILENAME%.*}"
          EXTRACTED_DIR="/workspace/output/$$BASENAME"
          
          if [ -d "$$EXTRACTED_DIR" ]; then
             echo "Uploading extracted images from $$EXTRACTED_DIR..."
             # Kopiujemy rekurencyjnie cały folder z obrazami
             gsutil cp -r "$$EXTRACTED_DIR" gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$$DATE/
             
             # 5. Generate latest.json for Web Flasher
             # Using the PUBLIC url for the web flasher to access
             PUBLIC_URL="https://storage.googleapis.com/${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$$DATE/$${BASENAME}/init_boot.img"
             echo "{\"date\":\"$$DATE\", \"id\":\"$$FILENAME\", \"image_url\":\"$$PUBLIC_URL\"}" > latest.json
             gsutil cp latest.json gs://${_BUCKET_NAME}/latest.json
          fi
        fi

  # 5. Deploy Web Flasher
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', 'web', 'gs://${_WEB_BUCKET_NAME}']

substitutions:
  _DEVICE_CODENAME: 'frankel'
  _BUCKET_NAME: ''      # Must be provided by the Trigger
  _CACHE_BUCKET_NAME: '' # Must be provided by the Trigger
  _WEB_BUCKET_NAME: ''   # Must be provided by the Trigger

timeout: '3600s' 
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY