steps:
  # 1. Pobierz ("Wypożycz") klucz z Secret Managera
  # To zapewnia, że klucz istnieje. Jeśli nie (błąd 404/403), build tutaj PADNIE i nie uruchomi kontenera.
  # Klucz trafia do wolumenu /workspace, który jest współdzielony i ulotny (znika po buildzie).
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'secrets'
      - 'versions'
      - 'access'
      - 'latest'
      - '--secret=avb-private-key'
      - '--outfile=cyber_rsa4096_private.pem'

  # 2. Zbuduj obraz (Docker) - BEZ KLUCZA
  # Dockerfile nie kopiuje klucza, bo go tam nie ma w kontekście (chyba że w workspace).
  # Ale lepiej uważać: Jeśli 'cyber_rsa4096_private.pem' leży w root, 'COPY src/ .' może go pominąć (bo src/),
  # ale upewnijmy się, że Dockerfile nie ma 'COPY . .'
  # Mój Dockerfile miał 'COPY src/ /app/'. Bezpiecznie.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'pixel-automator', '.']

  # 3. Uruchom Automator
  - name: 'pixel-automator'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Przenosimy klucz z workspace do miejsca, gdzie skrypt go szuka
        cp /workspace/cyber_rsa4096_private.pem /app/cyber_rsa4096_private.pem
        
        # Uruchamiamy
        python3 pixel_automator.py
    env:
      - '_DEVICE_CODENAME=${_DEVICE_CODENAME}'
      - '_BUCKET_NAME=${_BUCKET_NAME}'
    volumes:
      - name: 'build_output'
        path: '/app/output'

  # 4b. Upewnij się, że output jest dostępny (debug)
  - name: 'ubuntu'
    volumes:
      - name: 'build_output'
        path: '/workspace/output'
    args: ['ls', '-la', '/workspace/output']

    
  # 4. Wyślij wyniki
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    volumes:
      - name: 'build_output'
        path: '/workspace/output'
    args:
      - '-c'
      - |
        RESULT_FILE=$(find /workspace/output -name "ksu_patched_*.zip" | head -n 1)
        if [ ! -z "$RESULT_FILE" ]; then
          DATE=$(date +%Y%m%d)
          FILENAME=$(basename "$RESULT_FILE")
          # 1. Główny ZIP
          gsutil cp "$RESULT_FILE" gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$DATE/$FILENAME
          
          # 2. Sygnatura Custota
          if [ -f "$RESULT_FILE.csig" ]; then
             gsutil cp "$RESULT_FILE.csig" gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$DATE/$FILENAME.csig
          fi
          
          # 3. Raport JSON
          if [ -f "/workspace/output/build_status.json" ]; then
             gsutil cp /workspace/output/build_status.json gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$DATE/info.json
          fi
          
          # 4. Folder z obrazami (BOOT/INIT_BOOT + AVB Key)
          BASENAME="${FILENAME%.*}"
          EXTRACTED_DIR="/workspace/output/$BASENAME"
          
          if [ -d "$EXTRACTED_DIR" ]; then
             echo "Uploading extracted images from $EXTRACTED_DIR..."
             # Kopiujemy rekurencyjnie cały folder z obrazami
             gsutil cp -r "$EXTRACTED_DIR" gs://${_BUCKET_NAME}/builds/${_DEVICE_CODENAME}/$DATE/
          fi
        fi

substitutions:
  _DEVICE_CODENAME: 'frankel'
  _BUCKET_NAME: 'moj-pixel-bucket'

timeout: '3600s' 
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY