steps:
  # 0. Sprawdź dostępność Artifact Registry
  # Ten krok zapobiega uruchomieniu builda, jeśli repozytorium nie istnieje.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verifying Artifact Registry existence: ${_DOCKER_REPO_URL}"
        # Próbujemy wylistować obrazy (nawet pusta lista oznacza sukces = repo istnieje)
        if ! gcloud artifacts docker images list ${_DOCKER_REPO_URL} --limit=1 > /dev/null 2>&1; then
          echo "ERROR: Artifact Registry repository '${_DOCKER_REPO_URL}' does not exist or is not accessible."
          echo "Please ensure the Terraform infrastructure has been applied successfully."
          exit 1
        fi
        echo "Artifact Registry verified successfully."
  # 1. Pobierz ("Wypożycz") klucz z Secret Managera - REMOVED (Runtime Mount used instead)
  
  # 1. Spróbuj pobrać poprzednie obrazy (dla Cache'a)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_DOCKER_REPO_URL}/pixel-automator:latest > /dev/null 2>&1 || true; docker pull ${_DOCKER_REPO_URL}/pixel-automator:unstable > /dev/null 2>&1 || true']

  # 2. Zbuduj obraz jako :unstable
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_DOCKER_REPO_URL}/pixel-automator:unstable',
      '--cache-from', '${_DOCKER_REPO_URL}/pixel-automator:latest,${_DOCKER_REPO_URL}/pixel-automator:unstable',
      '.'
    ]

  # 3. Wypchnij obraz :unstable
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_DOCKER_REPO_URL}/pixel-automator:unstable']

  # 4. Zaktualizuj Joba do wersji :unstable (w celu testów)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Testing Candidate: ${_DOCKER_REPO_URL}/pixel-automator:unstable"
        gcloud run jobs update ${_REPO_NAME}-job \
          --image ${_DOCKER_REPO_URL}/pixel-automator:unstable \
          --region ${_REGION} \
          --memory 16Gi --cpu 4 \
          --set-env-vars=_DEVICE_CODENAME=${_DEVICE_CODENAME} \
          --set-env-vars=_BUCKET_NAME=${_BUCKET_NAME} \
          --set-env-vars=CACHE_BUCKET_NAME=${_CACHE_BUCKET_NAME} \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${PROJECT_ID}

  # 5. Uruchom testowo (Jeśli padnie, build się zatrzyma i nie nadpisze latest)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'jobs', 'execute', '${_REPO_NAME}-job', '--region', '${_REGION}', '--wait']

  # 6. PROMOCJA: Tagowanie unstable -> latest
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker tag ${_DOCKER_REPO_URL}/pixel-automator:unstable ${_DOCKER_REPO_URL}/pixel-automator:latest
        docker push ${_DOCKER_REPO_URL}/pixel-automator:latest

  # 7. Przywrócenie Joba na :latest (Dla harmonogramu)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Promoting to Stable: ${_DOCKER_REPO_URL}/pixel-automator:latest"
        gcloud run jobs update ${_REPO_NAME}-job \
          --image ${_DOCKER_REPO_URL}/pixel-automator:latest \
          --region ${_REGION} \
          --memory 16Gi --cpu 4 \
          --set-env-vars=GOOGLE_CLOUD_PROJECT=${PROJECT_ID}

  # 3. Build Web Interface (Vite/NPM)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd web
        npm ci
        npm run build
    id: 'npm-build'

  # 4. Deploy Web Assets to public bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if _WEB_BUCKET_NAME is set
        if [ -z "${_WEB_BUCKET_NAME}" ]; then
          echo "Error: _WEB_BUCKET_NAME is not set. Please update your Trigger or Terraform."
          exit 1
        fi
        
        # Clean destination first (optional but safer for Single Page Apps updates)
        gsutil -m rm -rf "gs://${_WEB_BUCKET_NAME}/**" || true
        
        # Sync dist folder with Cache-Control headers
        # HTML files: no-cache
        gsutil -m -h "Cache-Control:no-cache,max-age=0" rsync -r web/dist "gs://${_WEB_BUCKET_NAME}/"
    id: 'deploy-web'
    waitFor: ['npm-build']

substitutions:
  _DEVICE_CODENAME: 'frankel'
  _BUCKET_NAME: ''      # Must be provided by the Trigger
  _CACHE_BUCKET_NAME: '' # Must be provided by the Trigger
  _WEB_BUCKET_NAME: ''   # Must be provided by the Trigger

timeout: '3600s' 
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY